<?php //generated by soyshop 2015-03-14 13:19:50

class inquiry_html_page extends SOYShop_FreePageBase{

	function inquiry_html_page($args = array()){

		$this->setPageObject($args["page"]);

		WebPage::WebPage();

		/* write custom code here */
	}

	function main($args){
		/* write custom script here */



		/* --------------------- end */
	}
}


?>