<?php //generated by soyshop 2015-03-14 13:19:50

class item_list_page extends SOYShop_ListPageBase{

	function item_list_page($args = array()){

		$this->setPageObject($args["page"]);

		WebPage::WebPage();

		/* write custom code here */
	}

	function main($args){
		/* write custom script here */



		/* --------------------- end */
	}
}


?>